Добавляет функции получения рандомного целого числа и рандомного числ…
htmlacademy-javascript/154481-keksobooking-22 pull request #2
Opened 2021-02-03 21:14 UTC by WhaleisaJoy

…а с плавающей точкой

2021-02-04 06:23 UTC, craz3r requested changes

2021-02-04 06:23 UTC, craz3r commented on js/main.js
> +  return randomFloatNumberFixed;
Подумай как можно сократить код этой функции до одной строки с помощью функции getRandomNumber. Сейчас тело 2х функций почти полностью дублируется

2021-02-05 18:40 UTC, WhaleisaJoy commented on js/main.js
> +  return randomFloatNumberFixed;
Функцию сократила

2021-02-06 10:35 UTC, craz3r approved these changes

2021-02-06 10:35 UTC, merged